# Use the official Python base image
FROM python:3.11-slim
RUN pip config set global.index-url https://pypi.org/simple
RUN apt-get update \
    && apt-get install -y gcc libc-dev curl
WORKDIR /app
COPY requirements.txt .
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt --verbose --retries 3 --default-timeout=100 --timeout=1000
COPY . .
EXPOSE 8000

# Start the FastAPI server
CMD ["uvicorn", "app.main:app", "--proxy-headers", "--host", "0.0.0.0", "--port", "8000", "--workers", "4"]
