version: '3.12'

services:
  # FastAPI ML Inference Server
  fastapi-ml-inference:
    image: recommend_restaurant:latest 
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_URI=runs:/20667a37d29345be907ccc4007dd9978/recommend  # Change on your ML model path here
      - DATABASE_URL=postgresql://kuanggy:712211@localhost:5432/restaurant_recommmendation
      - MLFLOW_ARTIFACT_PATH=file:///Users/kuangsmacbook/Desktop/Works/LINEMAN MLE/attachment/mlruns/
    depends_on:
      - postgres

  # PostgreSQL Database Server
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=restaurant_recommmendation
      - POSTGRES_USER=kuanggy
      - POSTGRES_PASSWORD=712211
    ports:
      - "5432:5432"

  # MLflow Server
  mlflow:
    image: mlflow/mlflow:latest
    ports:
      - "5000:5000"
    environment:
      - BACKEND_STORE_URI=postgresql://ml_app_user:ml_app_password@postgres:5432/ml_app_db
      - ARTIFACT_STORE_URI=/mlflow/artifacts
    volumes:
      - ./mlflow:/mlflow
    depends_on:
      - postgres
