# Use a base image with MLflow dependencies
FROM python:3.11-slim
RUN apt-get update \
    && apt-get install -y curl \
    && rm -rf /var/lib/apt/lists/*
RUN pip install 'mlflow[extras]'
EXPOSE 4545
CMD ["mlflow", "server","--host", "0.0.0.0", "--port", "4545", "--backend-store-uri", "file:///Users/kuangsmacbook/Desktop/Works/LINEMANMLE/attachment/server/mlruns", "-w", "4"]
